
import 'dart:convert';

import '../../../../../../core/consts/api_const.dart';
import '../../../../../../core/network/network_helper.dart';
import '../models/user-view-inquiry-models.dart';

//true code now
class UserInquirysDataSource{

//send inquiry
  static Future<void> sendUserInquirys({
    required int hallId,
    required String message,
  })
  async{
    print("....... ApiConst.sendUserInquiry_hall.......");
    print(ApiConst.sendUserInquiry_hall);
    var response = await NetworkHelper().post( // or put  NetworkHelper().put()
      ApiConst.sendUserInquiry_hall,
      body: {
        'hall_id': hallId,
        'message':message,
      },
    );
    if(response.statusCode==201){
      print(".....true....");
      print("\n response sendUserInquirys :\n ${response.data} \n ");
    }else{
      print("\n status  :\n ${response.statusCode} \n ");
    }
    // String token = response.data['token'];
    // await Stor
    // ageHandler().setToken(token);
  }

  // جلب الاستفسارات من الـ API
  static Future<List<ViewQuiryRespModel>> fetchInquiries(int hallId_pub) async {
    try {
      final response = await NetworkHelper().get(ApiConst().fetchInquiries_response(hallId_pub));
      // dio.get(
      //   'http://192.168.43.31:8001/api/Client/myInquiries',
      //   options: Options(
      //     headers: {'Authorization': 'Bearer $token'},
      //   ),
      // );

      // التحقق من حالة الاستجابة
      if (response.statusCode == 200) {
        List<dynamic> data = response.data;
        return data.map((json) => ViewQuiryRespModel.fromJson(json)).toList();
      } else {
        throw Exception('Failed to load inquiries');
      }
    } catch (e) {
      throw Exception('Failed to load inquiries: $e');
    }
  }


// static Future<List<Conversation>> fetchInquiries() async {
  //   final response = await NetworkHelper().get(ApiConst().fetchInquiries_response);//dio.get(baseUrl);
  //   if (response.statusCode == 200) {
  //     List data = response.data as List;
  //     print('data......\n');
  //     print(data[0]['conversation']);
  //     return data.map((json) => Conversation.fromJson(json)).toList();
  //   } else {
  //     throw Exception('Failed to load inquiries');
  //   }
  // }

  // static Future<List<Autogenerated>> fetchInquiries() async {
  //   final response = await NetworkHelper().get(ApiConst().fetchInquiries_response);//dio.get(baseUrl);
  //   if (response.statusCode == 200) {
  //     List data = response.data as List;
  //     print('data......\n');
  //     print(data[0]['conversation']);
  //     return data.map((json) => Autogenerated.fromJson(json)).toList();
  //   } else {
  //     throw Exception('Failed to load inquiries');
  //   }
  // }



}